# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aca64e5394405e591f8731f2b13b34b491e788f4528e801dc5483f8f7e3e6dbe145853bc60dddaeb474963b25ffa6e1abe9f814d4947a811324607c0074857d

test:
  secret_key_base: 39d82e220f1d5e13559625a21d9c71f52465cbbdb06ab7b6804f3d68d1557aaa8f137de57be7007205e2a02ef9fee546a2c599cd203fa97b8fdd1a3b78c6ee44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
